### ISSUE TITLE
Many lint warnings and error

### ISSUE THREAD

**Issue by wowkin2** [coryhouse/pluralsight-redux-starter#21]
Node version:
`v6.3.1`
npm version:
`v3.10.3`
Operating system:
`Ubuntu 14.04 LTS`
Command line used:
`npm run build`
##### Steps to reproduce:
Try to run production server and lint will show many (443) similar warnings for most js files and 1 error.
As a result bundle js is not creating and routing show index.html instead.
```/home/username/WebstormProjects/sample_reactjs/webpack.config.dev-compiled.js (0/4)
  !   7:1  Unexpected var, use let or const instead  no-var
  !   9:1  Unexpected var, use let or const instead  no-var
  !  11:1  Unexpected var, use let or const instead  no-var
  !  13:1  Unexpected var, use let or const instead  no-var```

```/home/username/WebstormProjects/sample_reactjs/webpack.config.dev-compiled.js.map (1/0)
  ✖  1:11  Parsing error: Unexpected token :```

File webpack.config.dev-compiled.js.map starts with:
`{"version":3,"sources":["webpack.config.dev.js"],"names":[],.....`

**Comment by coryhouse** [comment]
You have changed the project, because webpack.config.dev-compiled.js isn't included in this kit. And I don't use the var keyword in web.config. I'd suggest using the final webpack.config that I build in the course. Since you're customizing the project, I'd suggest posting on Stack Overflow for Webpack specific issues.
